FROM flyway/flyway
WORKDIR /src
COPY  ./scripts/db_create.sql .
#ENTRYPOINT [ "flyway" migrate ]

ENTRYPOINT flyway  migrate  -user="sa" -password="Your_password123" -url="jdbc:sqlserver://db:1433;databaseName=teamfu" -locations="filesystem:." -baselineOnMigrate=true -baselineVersion=0


